WebApp/Controllers/InvoiceReportController.cs
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web.Mvc;
using AppService.Framework;
using AppService.Services;
using Domain.Global.Dto;
using Microsoft.Ajax.Utilities;
using WebApp.Helpers;
using WebApp.ViewModels.InvoiceReport;

namespace WebApp.Controllers
{
    [AuthenticationRequired]
    public class InvoiceReportController : BaseController
    {
        private readonly IInvoiceService _invoiceService;

        public InvoiceReportController(IInvoiceService invoiceService)
        {
            _invoiceService = invoiceService;
        }

        // GET: InvoiceReport
        [AuthenticationRequired]
        public ActionResult New()
        {
            return View();
        }

        [HttpPost]
        [AuthenticationRequired]
        public async Task<ActionResult> PrintReport(InvoiceReportDto invoiceReportDto)
        {
            if (!ModelState.IsValid)
                RedirectToHomeWithError(new ResponseModel
                {
                    Messages = new List<string> {"Ocurrio un Error con la Fechas Insertadas"}
                });

            var result = await _invoiceService.GetByDatesInterval(invoiceReportDto);

            if (!result.ExcecutedSuccesfully)
                RedirectToHomeWithError(result);

            var report = _invoiceService.GetInvoiceReport(result.Data);

            return FileAsStreamResult(report.Result.FileContent);
        }

        [HttpGet]
        [AuthenticationRequired]
        public async Task<ActionResult> Invoices(InvoiceReportDto invoiceReportDto)
        {
            if (invoiceReportDto.FromDate.IsNullOrWhiteSpace() || invoiceReportDto.ToDate.IsNullOrWhiteSpace())
            {
                RedirectToHomeWithError(new ResponseModel
                {
                    Messages = new List<string> {"Ocurrio un Error con la Fechas Insertadas"}
                });
            }
            var result = await _invoiceService.GetByDatesInterval(invoiceReportDto);

            if (!result.ExcecutedSuccesfully)
                RedirectToHomeWithError(result);

            var viewModel = new InvoiceReportViewModel
            {
                FromDate = result.Data.FirstOrDefault()?.FromDate,
                ToDate = result.Data.FirstOrDefault()?.ToDate,
                InvoiceReportDto = result.Data
            };

            return PartialView("~/Views/InvoiceReport/_list.cshtml", viewModel);
        }
    }
}

WebApp/Controllers/InvoiceReportDetailedController.cs
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web.Mvc;
using AppService.Framework;
using AppService.Services;
using Domain.Global.Dto;
using Microsoft.Ajax.Utilities;
using WebApp.Helpers;
using WebApp.ViewModels.InvoiceReport;

namespace WebApp.Controllers
{
    [AuthenticationRequired]
    public class InvoiceReportDetailedController : BaseController
    {
        private readonly IInvoiceService _invoiceService;

        public InvoiceReportDetailedController(IInvoiceService invoiceService)
        {
            _invoiceService = invoiceService;
        }

        // GET: InvoiceReport
        [AuthenticationRequired]
        public ActionResult New()
        {
            return View();
        }

        [HttpPost]
        [AuthenticationRequired]
        public async Task<ActionResult> PrintReport(InvoiceReportDto invoiceReportDto)
        {
            if (!ModelState.IsValid)
                RedirectToHomeWithError(new ResponseModel
                {
                    Messages = new List<string> {"Ocurrio un Error con la Fechas Insertadas"}
                });

            var result = await _invoiceService.GetByDatesInterval(invoiceReportDto);

            if (!result.ExcecutedSuccesfully)
                RedirectToHomeWithError(result);

            var report = _invoiceService.GetDetailedInvoiceReport(result.Data);

            return FileAsStreamResult(report.Result.FileContent);
        }

        [HttpGet]
        [AuthenticationRequired]
        public async Task<ActionResult> Invoices(InvoiceReportDto invoiceReportDto)
        {
            if (invoiceReportDto.FromDate.IsNullOrWhiteSpace() || invoiceReportDto.ToDate.IsNullOrWhiteSpace())
            {
                RedirectToHomeWithError(new ResponseModel
                {
                    Messages = new List<string> {"Ocurrio un Error con la Fechas Insertadas"}
                });
            }
            var result = await _invoiceService.GetByDatesInterval(invoiceReportDto);

            if (!result.ExcecutedSuccesfully)
                RedirectToHomeWithError(result);

            var viewModel = new InvoiceReportViewModel
            {
                FromDate = result.Data.FirstOrDefault()?.FromDate,
                ToDate = result.Data.FirstOrDefault()?.ToDate,
                InvoiceReportDto = result.Data
            };

            return PartialView("~/Views/InvoiceReportDetailed/_list.cshtml", viewModel);
        }
    }
}

WebApp/Views/InvoiceReportDetailed/New.cshtml
@model WebApp.ViewModels.InvoiceReport.InvoiceReportViewModel
@{
    ViewBag.Title = "Index";
}

@using (Html.BeginForm("PrintReport","InvoiceReport",FormMethod.Post, new {id="Invoice-report-form", enctype = "multipart/form-data" })) {

<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-lg-10">
        <h2>Reporte de Facturas Detallado</h2>
        <ol class="breadcrumb">
            <li>
                <a href="@Url.Action("Dashboard", "Home")">Home</a>
            </li>
            <li>
                Reportes
            </li>
            <li class="active">
                <strong>Reporte de Facturas Detallado</strong>
            </li>
        </ol>
    </div>
</div>
    <div class="wrapper wrapper-content animated fadeInRight white-bg m-t-lg">
        <div class="row">
            <div class="col-lg-3 col-md-3 col-xs-3">
                <div class="form-group">
                    <div class="group-date">
                        @Html.LabelFor(x => x.FromDate, new {@class = "control-label"})
                        <div class="input-group date col-md-12,">
                            <span class="input-group-addon"><i class="fa fa-calendar"></i></span><input type="text" class="form-control" id="FromDate" name="FromDate">
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-lg-3 col-md-3 col-xs-3">
                <div class="form-group">
                    <div class="group-date">
                        @Html.LabelFor(x => x.ToDate, new {@class = "control-label"})
                        <div class="input-group date ">
                            <span class="input-group-addon"><i class="fa fa-calendar"></i></span><input type="text" class="form-control" id="ToDate" name="ToDate">
                        </div>
                    </div>
                </div>
            </div>
            <div class="m-t-md" style="margin-top: 23px !important">
                <div class="col-lg-2 col-md-2 col-xs-1">
                    <div class="form-group">
                        <button class="btn btn-primary display-data" type="button" data-url-action=@Url.Action("Invoices")><i class="fa fa-search"></i> Consultar</button>
                    </div>
                </div>
                <div class="col-lg-2 col-md-2 col-xs-2"><div class="form-group">
                        <button type="submit" class="btn btn-default" id="printButton"><i class="fa fa-print"></i> Imprimir</button>
                    </div>
                </div>
            </div>
        </div>
        <div id="item-data" class="m-t-lg"></div>
    </div>
}
@section Styles{

    <link href="~/Content/plugins/datapicker/datepicker3.css" rel="stylesheet"/>
    <style>
        .btn { 
            white-space: normal !important;
        }
    </style>
}
@section Scripts{

    <script src="~/Scripts/plugins/datapicker/bootstrap-datepicker.js"></script>
    <script type="text/javascript">
        $(document)
            .ready(function() {
                $(".group-date .input-group.date")
                    .datepicker({
                        todayBtn: "linked",
                        keyboardNavigation: false,
                        forceParse: false,
                        calendarWeeks: true,
                        autoclose: true
                    });

                $(".input-group.date").datepicker("setDate", new Date());
                $(".input-group.date input").attr("readonly", "readonly");


                $(".display-data")
                    .click(function() {
                        debugger;
                        var command = $(this);
                        var url = command.attr("data-url-action");
                        var fromDate = $("#FromDate").val();
                        var toDate = $("#ToDate").val();
                        $.get(url,
                            {
                                FromDate: fromDate,
                                ToDate: toDate
                            },
                            function(data) {
                                var partialPage = $("#item-data");
                                partialPage.html();
                                partialPage.html(data);

                                if (!data.hasOwnProperty("ExcecutedSuccesfully"))
                                    return false;

                                if (data.ExcecutedSuccesfully.toString() === "true" ||
                                    data.ExcecutedSuccesfully.toString() === "True") {
                                    $("#printButton").removeAttr("disabled");

                                }
                            });
                    });
            });
    </script>

}

WebApp/Views/InvoiceReportDetailed/_list.cshtml
@model WebApp.ViewModels.InvoiceReport.InvoiceReportViewModel
<div class="table-responsive">
    <table class="table table-striped datatable">
        <thead>
            <tr>
                <th>No. Factura</th>
                <th>No. Factura</th>
                <th>Fecha Factura</th>
                <th>Cliente</th>
                <th>Procedimiento</th>
                <th>Precio</th>
                <th>Descuento</th>
                <th>Subtotal</th>
                <th>ITBIS %</th>
                <th>Total</th>
            </tr>
        </thead>
        <tbody>
            @{
                if (!Model.InvoiceReportDto.Any())
                {
                    <tr>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td>
                            <div class="font-bold"> No se encontraron resultados para esta Busqueda </div>
                        </td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                    </tr>
                }
                else
                {
                    foreach (var invoice in Model.InvoiceReportDto)
                    {
                        <tr>
                            <td>@invoice.InvoiceNumber</td>
                            <td></td>
                            <td>@invoice.InvoiceDate</td>
                            <td>@invoice.CustomerName</td>
                            <td>@invoice.ClinicalProcedure</td>
                            <td>
                                <div class="text-right">@invoice.Price</div>
                            </td>
                            <td>
                                <div class="text-right">@invoice.Discount</div>
                            </td>
                            <td>
                                <div class="text-right">@invoice.Subtotal</div>
                            </td>
                            <td>
                                <div class="text-right">@invoice.Tax</div>
                            </td>
                            <td>
                                <div class="text-right">@invoice.Total</div>
                            </td>
                        </tr>
                    }

                }

            }
        </tbody>
    </table>
</div>

<script type="text/javascript">
    $(document).ready(function() {
        // Jquery Datatable
        $(".datatable")
            .dataTable({
                language: {
                    url: "../Scripts/plugins/dataTables/Spanish.json"
                },
                "columnDefs": [
                   { "visible": false, "targets": 0 }
                ],
                "order": [],
                "drawCallback": function (settings) {
                    var api = this.api();
                    var rows = api.rows({ page: 'current' }).nodes();
                    var last = null;

                    api.column(0, { page: 'current' })
                        .data()
                        .each(function (group, i) {
                            if (last !== group) {
                                $(rows)
                                    .eq(i)
                                    .before(
                                        '<tr class="group"><td colspan="9"><strong>' + group + '</strong></td></tr>'
                                    );

                                last = group;
                            }
                        });
                },
            });

    });
</script>