WebApp/ViewModels/Supplier/CreateSupplierViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace WebApp.ViewModels
{
    public class CreateSupplierViewModel
    {
        public string Name { get; set; }
        public string Address { get; set; }
        public string Phone { get; set; }
    }
}

WebApp/ViewModels/Supplier/JsonFeedSupplierViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace WebApp.ViewModels
{
    public class JsonFeedSupplierViewModel
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public string Phone { get; set; }

        public static List<JsonFeedSupplierViewModel> SupplierList()
        {
            return new List<JsonFeedSupplierViewModel>()
            {
                new JsonFeedSupplierViewModel()
                {
                    Id =1,
                    Name = "Dentist CxA",
                    Address = "C/ Roberto Pasteuriza # 8",
                    Phone = "809-334-8365"
                },
                new JsonFeedSupplierViewModel()
                {
                    Id =2,
                    Name = "Teeth CxA",
                    Address = "Ave Castellanos # 1",
                    Phone = "809-454-5656"
                },
                new JsonFeedSupplierViewModel()
                {
                    Id =3,
                    Name = "Braquets CxA",
                    Address = "C/ Roberto Pasteuriza # 8",
                    Phone = "809-334-8365"
                },
            };
        }
    }

}

WebApp/ViewModels/Supplier/UpdateSuplierViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace WebApp.ViewModels
{
    public class UpdateSuplierViewModel
    {
        public int Id { get; set; }
        [Display(Name = "Compañia")]
        public string Name { get; set; }
        [Display(Name = "Direccion")]
        public string Address { get; set; }
        [Display(Name = "Telefono")]
        public string Phone { get; set; }
    }
}

WebApp/Controllers/InventoryController.cs
using AppService.Framework;
using AppService.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using WebApp.Helpers;
using WebApp.ViewModels;
using WebApp.ViewModels.Product;

namespace WebApp.Controllers
{
    //[AuthenticationRequired]
    public class InventoryController : Controller
    {

        private readonly ISupplierService _supplierService;
        private readonly IProductService _productService;
        private readonly IInventoryTransactionService _inventoryTransactionService;

        public InventoryController(ISupplierService supplierService, IProductService productService, IInventoryTransactionService inventoryTrasnactionService)
        {
            _supplierService = supplierService;
            _productService = productService;
            _inventoryTransactionService = inventoryTrasnactionService;
        }
        // GET: Inventory
        public ActionResult Materials()
        {
          
            return View();
        }
        public ActionResult Suppliers()
        {

            return View();
        }
        public ActionResult Transactions()
        {
           
            return View();
        }

        public async Task<JsonResult> ProductsFeed()
        {
            var response = await _productService.GetProducts();
            var products = new List<JsonFeedProdcutViewModel>();
            foreach(var data in response.Data)
            {
                JsonFeedProdcutViewModel productfeed = new JsonFeedProdcutViewModel();
                productfeed.Id = data.Id;
                productfeed.Name = data.Name;
                productfeed.Brand = data.Brand;
                productfeed.Quantity = data.Quantity;
                productfeed.UnitCost = data.UnitCost;
                for(int i = 0; i < data.Suppliers.Count; i++)
                {
                    if (data.Suppliers.ElementAt(i).IsDeleted)
                    {
                        continue;
                    }
                    productfeed.Suppliers += data.Suppliers.ElementAt(i).Name;
                    productfeed.SupplierIds += data.Suppliers.ElementAt(i).Id;
                    if ((i+1) != data.Suppliers.Count)
                    {
                        productfeed.Suppliers += "<br/>";
                        productfeed.SupplierIds += ",";
                    }
                }

                products.Add(productfeed);
            }
            return Json(products, JsonRequestBehavior.AllowGet);
        }
        public async Task<JsonResult> CreateProduct(CreateProductViewModel product)
        {
            var response = await _productService.CreateProduct(product.Name,product.Brand,product.SupplierId,product.UnitCost,product.Quantity);
            return Json(response, JsonRequestBehavior.AllowGet);
        }

        public async Task<JsonResult> UpdateProduct(ProductViewModel product)
        {
            var response = await _productService.UpdateProduct(product.Id,product.Name, product.Brand, product.SupplierId, product.UnitCost);
            return Json(response.ExcecutedSuccesfully, JsonRequestBehavior.AllowGet);
        }

        public async Task<JsonResult> RemoveProduct(InventoryTransactionViewModel inventoryTransation)
        {
            var response = await _productService.RemoveProduct(inventoryTransation.ProductId, inventoryTransation.Quantity, inventoryTransation.Type);
            return Json(response, JsonRequestBehavior.AllowGet);
        }

        public async Task<JsonResult> AddProduct(InventoryTransactionViewModel inventoryTransation)
        {
            var response = await _productService.AddProduct(inventoryTransation.ProductId, inventoryTransation.Quantity, inventoryTransation.Type);
            return Json(response, JsonRequestBehavior.AllowGet);
        }

        public async Task<JsonResult> SuppliersFeed()
        {
            var response = await _supplierService.GetSuppliers();
            var suppliers = new List<JsonFeedSupplierViewModel>();
            if (response.ExcecutedSuccesfully)
            {
                foreach (var supplier in response.Result)
                {
                    suppliers.Add(new JsonFeedSupplierViewModel()
                    {
                        Id = supplier.GetType().GetProperty("Id").GetValue(supplier),
                        Name = supplier.GetType().GetProperty("Name").GetValue(supplier),
                        Phone = supplier.GetType().GetProperty("Phone").GetValue(supplier),
                        Address = supplier.GetType().GetProperty("Address").GetValue(supplier)
                    });
                }
            }
            return Json(suppliers, JsonRequestBehavior.AllowGet);
        }

        public async Task<JsonResult> CreateSupplier(CreateSupplierViewModel supplier)
        {
            var response = await _supplierService.CreateSupplier(supplier.Name, supplier.Phone, supplier.Address);
            var suppliers = new UpdateSuplierViewModel();
            if (response.ExcecutedSuccesfully)
            { 
                suppliers = new UpdateSuplierViewModel()
                {
                    Id= response.Result.GetType().GetProperty("Id").GetValue(response.Result,null),
                    Name = supplier.Name,
                    Address = supplier.Address,
                    Phone = supplier.Phone
                };
            }
            return Json(suppliers, JsonRequestBehavior.AllowGet);
        }
        
        public async Task<JsonResult> SoftDeleteSupplier(int supplierId =0)
        {
            var response = await _supplierService.SoftDeleteSupplier(supplierId);
            return Json(response, JsonRequestBehavior.AllowGet);
        }

        public async Task<JsonResult> UpdateSupplier(UpdateSuplierViewModel supplier)
        {

            var response = await _supplierService.UpdateSupplier(supplier.Id, supplier.Name, supplier.Phone, supplier.Address);
            if (response.ExcecutedSuccesfully)
            {
                supplier = new UpdateSuplierViewModel();
            }
            return Json(supplier, JsonRequestBehavior.AllowGet);
        }

        public async Task<JsonResult> InventoryTransactionFeed()
        {
            var response = await _inventoryTransactionService.GetInventoryTransaction();
            var itransactions = new List<JsonFeedInvenotryTransaccionViewModel>();
            if (response.ExcecutedSuccesfully)
            {
                foreach (var it in response.Result)
                {
                    var product = it.GetType().GetProperty("Product").GetValue(it, null);
                    itransactions.Add(new JsonFeedInvenotryTransaccionViewModel()
                    {
                        Id = it.GetType().GetProperty("Id").GetValue(it,null),
                        CreatedOn = (it.GetType().GetProperty("CreatedOn").GetValue(it, null)).ToString("dd'/'MM'/'yyyy"),
                        ProductId = it.GetType().GetProperty("ProductId").GetValue(it, null),
                        ProductName = product.Name + " " + product.Brand,
                        Quantity = it.GetType().GetProperty("Quantity").GetValue(it, null),
                        Type = (int) it.GetType().GetProperty("Type").GetValue(it, null),
                        TypeDescripcion = (((int)it.GetType().GetProperty("Type").GetValue(it, null)) == 1 ? "Salida" : "Entrada")
                    });
                   
                }
            }
            return Json(itransactions, JsonRequestBehavior.AllowGet);
        }

        public async Task<JsonResult> RollBackTransaction (int inventoryTransactionId)
        {
            var response = await _inventoryTransactionService.RollBackTransaction(inventoryTransactionId);
            return Json(response, JsonRequestBehavior.AllowGet);
        }

        public async Task<JsonResult> UpdateTransaction(UpdateInventoryTransactionViewModel invTransation)
        {
            var response = await _inventoryTransactionService.UpdateTransaction(invTransation.Id, invTransation.Type, invTransation.Quantity);
            return Json(response, JsonRequestBehavior.AllowGet);
        }
    }
}

WebApp/Views/Inventory/Transactions.cshtml
@model JsonFeedInvenotryTransaccionViewModel
@{
    ViewBag.Title = "Movimientos";
}
<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-lg-10">
        <h2>Movimientos del Inventario</h2>
        <ol class="breadcrumb">
            <li>
                <a href="@Url.Action("Dashboard", "Home")">Home</a>
            </li>
            <li>
                Inventario
            </li>
            <li class="active">
                <strong>Movimientos</strong>
            </li>
        </ol>
    </div>
    <div class="col-lg-2">

    </div>
</div>
<!--Inventory transaction Table-->
<div class="wrapper wrapper-content animated fadeInRight white-bg m-t-lg">
   
    <div class="row">
        <div class="col-lg-12 col-xs-12">
            <div class="table-responsive">
                <table class="table  table-bordered  dataTables-example table-hover" style="width:100%;">
                    <thead>
                        <tr>
                            <th>ID</th>
                            <th>Fecha</th>
                            <th>ProductoID</th>
                            <th>Producto</th>
                            <th>Cantidad</th>
                            <th>Tipo</th>
                            <th>Movimiento</th>
                            <th>Option</th>
                        </tr>
                    </thead>
                   
                </table>
            </div>
        </div>
    </div>
</div>
<!--Modify Inventory transaction Modal-->
<div class="modal fade" id="ModifyTransactionModal" style="overflow:hidden;" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="exampleModalLabel">Modificar Transaccion</h4>
            </div>
            @using (Html.BeginForm("UpdateTransaction", "Inventory", FormMethod.Post, new { @class = "form-horizontal", id = "UpdateTransactionForm" }))
            {
                <div class="modal-body">
                    @Html.HiddenFor(x => x.Id )
                    <input type="hidden" name="Type" id="Type" value="" />
                    <div class="form-group">
                        <div class="row">
                            <div class="col-lg-11 col-xs-12">
                                <label class="control-label">Informacion del producto</label>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-lg-11 col-xs-12">
                                @Html.TextBoxFor(x => x.ProductName, new { @class = "form-control", placeholder = "Articulo", minlength = "2", tabindex = "1", required = "", disabled = "" })
                            </div>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="row">
                            <div class="col-lg-11 col-xs-12">
                                @Html.LabelFor(x => x.Quantity , new { @class = "control-label" })
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-lg-11 col-xs-12">
                                @Html.TextBoxFor(x => x.Quantity, new { @class = "form-control", placeholder = "Cantidad", tabindex = "5", type = "number", min = "0", required = "" })
                            </div>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <a class="btn btn-default" data-dismiss="modal">Cancelar</a>
                    <button class="btn btn-primary create-product">Guardar</button>
                </div>
            }
        </div>
    </div>
</div>

@section Styles {
    @Styles.Render("~/Content/plugins/dataTables/dataTablesStyles")
    @Styles.Render("~/plugins/jasnyBootstrapStyles")
    @Styles.Render("~/plugins/sweetAlertStyles")
    @Styles.Render("~/plugins/tooltipsterStyles")
    <style>
        .add-row{
            background-color:#B2DFDB;
        }
        .remove-row{
           background-color:#EF9A9A
        }
        .tooltip-clear,
        .create-supplier,
        .delete-supplier,
        .update-supplier {
        }
    </style>

}

@section Scripts {
    @Scripts.Render("~/plugins/dataTables")
    @Scripts.Render("~/plugins/jasnyBootstrap")
    @Scripts.Render("~/plugins/sweetAlert")
    @Scripts.Render("~/plugins/validate")
    @Scripts.Render("~/plugins/tooltipster")
    @Scripts.Render("~/plugins/momentjs")
    <script src="https://cdn.datatables.net/plug-ins/1.10.12/dataRender/datetime.js"></script>

    <script type="text/javascript">
    $(document).ready(function () {
        $.fn.dataTable.ext.errMode = 'throw';
        $('.dataTables-example').DataTable({
            pageLength: 10,
            dom: '<"html5buttons"B>lTfgitp',
            "language": {
                "emptyTable": "<strong>No hay registros disponibles</strong>",
                "lengthMenu": "Mostrando _MENU_ Registros por pagina",
                "zeroRecords": "No se encontro nada con el criterio de busqueda",
                "info": "Pagina _PAGE_ de _PAGES_",
                "infoEmpty": "No hay registros disponibles",
                "infoFiltered": "",
                "search": "<span class='fa fa-search m-r-xs' ></span>Buscar:",
                "paginate": {
                    "next": "Proximo",
                    "previous": "Anterior"
                }
            },
            ajax: {
                url: '@Url.Action("InventoryTransactionFeed", "Inventory")',
                dataSrc: ''
            },
            columns: [
                { "data": "Id" },
                { "data": "CreatedOn" },
                { "data": "ProductId" },
                { "data": "ProductName" },
                { "data": "Quantity" },
                { "data": "Type" },
                { "data": "TypeDescripcion" },
                { "data": null }
            ],
            "columnDefs": [
                  {
                      "targets": [5],
                      "visible": false,
                      "searchable": false
                  },
                  {
                    "targets": 1,
                    "render": $.fn.dataTable.render.moment('DD/MM/YYYY', 'DD/MM/YYYY')
                  },
                    {
                        "targets": -1,
                        "data": null,
                        "defaultContent": '<span data-toggle="modal" data-target="#ModifyTransactionModal"><button class="btn btn-xs btn-success m-l-xs modify-transaction" data-toggle="tooltip" title="Actualizar"><span class="fa fa-refresh"></span></button></span>' +
                                          '<button class="m-l-xs btn btn-xs btn-danger restore-transaction" data-toggle="tooltip" title="Eliminar"><span class="fa fa-times"></span></button>'
                    }
            ],
            "order": [
                [1, "desc"]
            ],
            "createdRow": function ( row, data, index ) {
                if ( data.Type > 1 ) {
                    $(row).addClass('add-row');
                } else {
                    $(row).addClass('remove-row');
                }
            },
            buttons: [
                { extend: 'copy', exportOptions: { columns: [0, 1, 2, 3, 4, 5] } },
                { extend: 'csv', exportOptions: { columns: [0, 1, 2, 3, 4, 5] } },
                { extend: 'excel',exportOptions:{columns: [0, 1, 2, 3,4, 5]}, title: 'Lista de Clientes' },
                { extend: 'pdf', exportOptions: { columns: [0, 1, 2, 3, 4, 5] }, title: 'Lista de Clientes' },

                {
                    extend: 'print',
                    exportOptions:{columns: [0, 1, 2, 3,4, 5]},
                    customize: function (win) {
                        $(win.document.body).addClass('white-bg');
                        $(win.document.body).css('font-size', '10px');

                        $(win.document.body).find('table')
                                .addClass('compact')
                                .css('font-size', 'inherit');
                    }
                }
            ]

        });

        var table = $('.dataTables-example').DataTable();


        //custom code
        $('.dataTables-example tbody').on('click', 'tr', function () {
            $(this).addClass('seleted-tr').siblings().removeClass('seleted-tr');
            let data = table.row(this).data();
            if (!table.data().count()) {
                return 0;
            }
            loadUpdateTransactionForm(data);
            toggleRemoveAddProductButtons(1)
        });
        function clearToolTip() {
            var instances = $.tooltipster.instances();
            $.each(instances, function (i, instance) {
                instance.close();
            });
        }
        function loadUpdateTransactionForm(data) {
            $('#UpdateTransactionForm input#Id').val(data.Id);
            $('#UpdateTransactionForm input#ProductName').val(data.ProductName);
            $('#UpdateTransactionForm input#Quantity').val(data.Quantity);
        }

        function toggleRemoveAddProductButtons(action) {
            if (action == 2) {
                $('.restore-transaction').prop('disabled', true);
                $('.restore-transaction').removeClass('btn-danger').addClass('btn-default');
                $('.modify-transaction').prop('disabled', true);
                $('.modify-transaction').removeClass('btn-success').addClass('btn-default');
            }
            else {
                $('.restore-transaction').prop('disabled', false);
                $('.restore-transaction').removeClass('btn-default').addClass('btn-danger');
                $('.modify-transaction').prop('disabled', false);
                $('.modify-transaction').removeClass('btn-default').addClass('btn-success');
            }
        }

        $('body').on('click', '.restore-transaction', function (event) {
            swal({
                title: "Deshacer la transaction?",
                text: "",
                type: "warning",
                showCancelButton: true,
                confirmButtonClass: "btn-warning",
                confirmButtonText: "Si",
                cancelButtonText:"No",
                closeOnConfirm: false
            },
           function (isConfirm) {
               if (isConfirm) {
                   let data = table.row('.seleted-tr').data();
                   let supplier = { inventoryTransactionId : data.Id };
                   let jsondata = JSON.stringify(supplier);
                   $.ajax({
                       url:'@Url.Action("RollBackTransaction", "Inventory")',
                       dataType: 'json',
                       contentType: 'application/json; charset=UTF-8',
                       type: 'POST',
                       data: jsondata,
                       success: function (data) {
                           swal({
                               title: "Transaccion Restaurada",
                               text: " ",
                               type: "success",
                               confirmButtonClass: "btn-success",
                               confirmButtonText: "Ok!",
                               closeOnConfirm: true
                           },
                           function () {
                               table.ajax.reload();
                               $('#UpdateSupplierModal').modal('hide');
                           });
                       }
                   });
               }
           });
        });

        $('#UpdateTransactionForm').submit(function (event) {
            var formdata = new FormData($(this).get(0));
            var form = $(this);
            $.ajax({
                dataType: 'JSON',
                type: 'POST',
                url: form.attr('action'),
                data: formdata,
                processData: false,
                contentType: false,
                success: function (r) {
                    swal({
                        title: "Transaction Modificada!",
                        text: " ",
                        type: "success",
                        confirmButtonClass: "btn-success",
                        confirmButtonText: "Ok!",
                        closeOnConfirm: true
                    },
                    function () {
                        table.ajax.reload();
                        $('#ModifyTransactionModal').modal('hide');
                    });
                },
                error: function (jqXHR, textStatus, errorThrown) {
                    sweetAlert('ERROR', 'No hay coneccion al servidor', 'error');
                }
            });
            return false;
        });

        //clean 1st form inside a modal
        $('.modal').on('hidden.bs.modal', function (e) {
            $(this).find('form')[0].reset();
        });



    })
    </script>
}