WebApp/ViewModels/Dashboard/DashboardViewModel.cs
using Data.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace WebApp.ViewModels
{
    public class DashboardViewModel
    {
        public int TodayAppointmentsCount { get; set; }
        public int ThisMonthAppointmentsCount { get; set; }
        public decimal TodayIncome { get; set; }
        public decimal ThisMonthIncome { get; set; }
        public List<Appointment> TodayAppointment { get; set;}
    }
}

WebApp/Controllers/AgendaController.cs
using AppService.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using WebApp.ViewModels;
using Data.Entities;
using AppService.Framework;
using WebApp.Helpers;

namespace WebApp.Controllers
{
    //Thinking of calling Appointment Controller
    //Agenda Views & Appointment related Json feed
    [AuthenticationRequired]
    public class AgendaController : BaseController
    {

        private readonly IAppointmentService _appointmentService;
        private readonly IPatientService _patientService;

        public AgendaController(IAppointmentService appointmentService, IPatientService patientService)
        {
            _appointmentService = appointmentService;
            _patientService = patientService;
        }
        //Make Appoinment
        [ReferrOnly]
        //[Secretary]
        //[CheckAccess]
        public async Task<ActionResult> MakeAppointment( int id)
        {
            var response = await _patientService.GetPatient(id);
            if (response.ExcecutedSuccesfully) {
                var patient = response.Result;
                JsonFeedPatientViewModel selectedPatients = new JsonFeedPatientViewModel()
                {
                    Id = patient.GetType().GetProperty("Id").GetValue(patient, null),
                    Name = patient.GetType().GetProperty("Name").GetValue(patient, null),
                    LastName = patient.GetType().GetProperty("LastName").GetValue(patient, null),
                    Birthday = (patient.GetType().GetProperty("Birthday").GetValue(patient, null)).ToString("dd'/'MM'/'yyyy"),
                    Email = patient.GetType().GetProperty("Email").GetValue(patient, null)
                };
                var phones = patient.GetType().GetProperty("Phones").GetValue(patient, null);
                foreach (var phone in phones)
                {
                    if (phone.GetType().GetProperty("Primary").GetValue(phone, null) == 1)
                    {
                        selectedPatients.PhoneNumber = phone.GetType().GetProperty("Number").GetValue(phone, null);
                        selectedPatients.PhoneType = phone.GetType().GetProperty("Type").GetValue(phone, null);
                    }

                }
                return View(selectedPatients);
            }
            return View();
        }
        //Manage schedule
        //[Secretary]
        //[CheckAccess]
        public ActionResult Scheduler()
        {
            return View();
        }

        [Dentist]
        [CheckAccess]
        public ActionResult DentistAgenda()
        {
            ViewBag.UserId = SessionHelper.GetUser();
            return View();
        }

        public async Task<JsonResult> AppointmentsFeed( )
        {
            var response = await _appointmentService.GetAppointments( ).ConfigureAwait(false);
            var appointments = new List<JsonFeedAppointmentViewModel>();
            foreach(var appoinment in response.Result)
            {
                var patient = appoinment.GetType().GetProperty("Patient").GetValue(appoinment, null);
                var user = appoinment.GetType().GetProperty("User").GetValue(appoinment, null);
                appointments.Add(new JsonFeedAppointmentViewModel()
                {
                    Id = appoinment.GetType().GetProperty("Id").GetValue(appoinment, null),
                    StartDate =(appoinment.GetType().GetProperty("StartDate").GetValue(appoinment, null)).ToString("yyyy-MM-ddTHH:mm:ss"),
                    EndDate = (appoinment.GetType().GetProperty("EndDate").GetValue(appoinment, null)).ToString("yyyy-MM-ddTHH:mm:ss"),
                    Description = appoinment.GetType().GetProperty("Description").GetValue(appoinment, null),
                    UserId = appoinment.GetType().GetProperty("UserId").GetValue(appoinment, null),
                    IsUserDeleted = user.GetType().GetProperty("IsDeleted").GetValue(user,null),
                    PatientId = appoinment.GetType().GetProperty("PatientId").GetValue(appoinment, null),
                    IsPaid = appoinment.GetType().GetProperty("IsPaid").GetValue(appoinment, null),
                    PatientName = patient.GetType().GetProperty("Name").GetValue(patient, null) + " "+
                                    patient.GetType().GetProperty("LastName").GetValue(patient, null)

                });
            }
              
           
            return Json(appointments, JsonRequestBehavior.AllowGet);
        }

        public async Task<JsonResult> AppointmentsFeedByDentistId(int dentistId)
        {
            var response = await _appointmentService.GetAppointmentsByDentistId(dentistId).ConfigureAwait(false);
            var appointments = new List<JsonFeedAppointmentViewModel>();
            foreach (var appoinment in response.Result)
            {
                var patient = appoinment.GetType().GetProperty("Patient").GetValue(appoinment, null);
                appointments.Add(new JsonFeedAppointmentViewModel()
                {
                    Id = appoinment.GetType().GetProperty("Id").GetValue(appoinment, null),
                    StartDate = (appoinment.GetType().GetProperty("StartDate").GetValue(appoinment, null)).ToString("yyyy-MM-ddTHH:mm:ss"),
                    EndDate = (appoinment.GetType().GetProperty("EndDate").GetValue(appoinment, null)).ToString("yyyy-MM-ddTHH:mm:ss"),
                    Description = appoinment.GetType().GetProperty("Description").GetValue(appoinment, null),
                    UserId = appoinment.GetType().GetProperty("UserId").GetValue(appoinment, null),
                    PatientId = appoinment.GetType().GetProperty("PatientId").GetValue(appoinment, null),
                    PatientName = patient.GetType().GetProperty("Name").GetValue(patient, null) + " " +
                                    patient.GetType().GetProperty("LastName").GetValue(patient, null)

                });
            }


            return Json(appointments, JsonRequestBehavior.AllowGet);
        }

        public async Task<JsonResult> CancelAppointment(int appointmentId)
        {
            
            var response = await _appointmentService.DeleteAppointment(appointmentId);
            return Json(response, JsonRequestBehavior.AllowGet);

        }

        public async Task<JsonResult> ConfirmAppointment(int appointmentId)
        {

            var response = await _appointmentService.ConfirmAppointment(appointmentId);
            return Json(response, JsonRequestBehavior.AllowGet);

        }

        public async Task<JsonResult> UpdateAppointment(UpdateAppointmentViewModel appointment)
        {
            
                var response = await _appointmentService.UpdateAppointment(appointment.Id, appointment.StartDate, appointment.EndDate, appointment.PatientId, appointment.UserId);
                return Json(response, JsonRequestBehavior.AllowGet);
            
        }

        public async Task<JsonResult> setAppointment(CreateAppointmentViewModel appointment)
        {
            var response = await _appointmentService.CreateAppointment(appointment.StartDate, appointment.EndDate, appointment.PatientId, appointment.UserId);
            if (response.ExcecutedSuccesfully)
            {
                appointment.Id = response.Result.GetType().GetProperty("Id").GetValue(response.Result, null);
            }

            return Json(appointment,JsonRequestBehavior.AllowGet);
        }
    }
}

WebApp/Controllers/HomeController.cs
using System.Web.Mvc;
using AppService.Services;
using Domain.Global.Enums;
using Domain.Global.Extensions;
using WebApp.Helpers;
using WebApp.ViewModels;
using System.Globalization;
using System;
using System.Threading.Tasks;

namespace WebApp.Controllers
{
    [AuthenticationRequired]
    public class HomeController : BaseController
    {
        private readonly IAppointmentService _appointmentService;
        private readonly IInvoiceService _invoiceService;

        public HomeController( IAppointmentService appointmentService,IInvoiceService invoiceService)
        {
            _invoiceService = invoiceService;
            _appointmentService = appointmentService;
        }

        // GET: Home
        public async Task<ActionResult> Dashboard()
        {
            var dashboardModel = new DashboardViewModel();
            var today = DateTime.Now;
            var firstInterval = today.Year + "-" + (today.Month > 9 ? today.Month.ToString() : "0" + today.Month) + '-' + (today.Day > 9 ? today.Day.ToString() : "0" + today.Day) + "T00:00:00";
            var lastInterval = today.Year + "-" + (today.Month > 9? today.Month.ToString():"0"+ today.Month) + '-' + (today.Day > 9 ? today.Day.ToString() : "0" + today.Day) + "T23:59:59";
            var todayAppointmentresult = await _appointmentService.GetAppointmentsByDateInterVal(DateTime.ParseExact(firstInterval, "yyyy-MM-ddTHH:mm:ss", CultureInfo.InvariantCulture), DateTime.ParseExact(lastInterval, "yyyy-MM-ddTHH:mm:ss", CultureInfo.InvariantCulture));
            if (todayAppointmentresult.ExcecutedSuccesfully)
            {
                if(todayAppointmentresult.Data != null)
                {
                    dashboardModel.TodayAppointment = todayAppointmentresult.Data;
                    dashboardModel.TodayAppointmentsCount = todayAppointmentresult.Data.Count;
                }else
                {
                    dashboardModel.TodayAppointmentsCount = 0;
                }
            }
            var todayIncomeResult = await _invoiceService.GetInvoiceByDateInterval(DateTime.ParseExact(firstInterval, "yyyy-MM-ddTHH:mm:ss", CultureInfo.InvariantCulture), DateTime.ParseExact(lastInterval, "yyyy-MM-ddTHH:mm:ss", CultureInfo.InvariantCulture));
            if (todayIncomeResult.ExcecutedSuccesfully)
            {
                if (todayIncomeResult.Data != null)
                {
                    decimal todayIncome = 0;
                    foreach(var invoice in todayIncomeResult.Data)
                    {
                        foreach (var invoiceDetails in invoice.InvoiceDetails)
                        {
                            todayIncome += invoiceDetails.MedicalProcedurePrice;
                        }
                    }
                    dashboardModel.TodayIncome = todayIncome;
                }
                else
                {
                    dashboardModel.TodayIncome = 0;
                }
            }
            firstInterval = today.Year + "-" + (today.Month > 9 ? today.Month.ToString() : "0" + today.Month) + '-' + "01T00:00:00";
            lastInterval = today.Year + "-" + ((today.Month+1) > 9 ? (today.Month+1).ToString() : "0" + (today.Month+1)) + '-' + "01T00:00:00";
            var thisMonthAppointmentResult = await _appointmentService.GetAppointmentsByDateInterVal(DateTime.ParseExact(firstInterval, "yyyy-MM-ddTHH:mm:ss", CultureInfo.InvariantCulture), DateTime.ParseExact(lastInterval, "yyyy-MM-ddTHH:mm:ss", CultureInfo.InvariantCulture));
            if (thisMonthAppointmentResult.ExcecutedSuccesfully)
            {
                if (thisMonthAppointmentResult.Data != null)
                {
                    dashboardModel.ThisMonthAppointmentsCount = thisMonthAppointmentResult.Data.Count;
                }else
                {
                    dashboardModel.ThisMonthAppointmentsCount = 0;
                }
            }
            var thisMonthIncomeResult = await _invoiceService.GetInvoiceByDateInterval(DateTime.ParseExact(firstInterval, "yyyy-MM-ddTHH:mm:ss", CultureInfo.InvariantCulture), DateTime.ParseExact(lastInterval, "yyyy-MM-ddTHH:mm:ss", CultureInfo.InvariantCulture));
            if (thisMonthIncomeResult.ExcecutedSuccesfully)
            {
                if (thisMonthIncomeResult.Data != null)
                {
                    decimal thisMonthIncome = 0;
                    foreach (var invoice in thisMonthIncomeResult.Data)
                    {
                        foreach (var invoiceDetails in invoice.InvoiceDetails)
                        {
                            thisMonthIncome += invoiceDetails.MedicalProcedurePrice;
                        }
                    }
                    dashboardModel.ThisMonthIncome = thisMonthIncome;
                }
                else
                {
                    dashboardModel.ThisMonthIncome = 0;
                }
            }
            return View(dashboardModel);
        }

        public JsonResult ToDoListAdd(string reminder)
        {
            return Json("", JsonRequestBehavior.AllowGet);
        }

        public JsonResult ToDoListDelete(int id)
        {
            return Json("", JsonRequestBehavior.AllowGet);
        }

        public ActionResult ErrorPage(ErrorViewModel viewModel)
        {
            //var todayAppointments = _appointmentService
            return View(viewModel);
        }
    }
}

WebApp/Views/Home/Dashboard.cshtml
@model DashboardViewModel
@{
    ViewBag.Title = "Dashboard";
    ViewBag.name = (string)Session["UserName"] ?? " ";
    string role = (string)Session["UserRoles"] ?? " ";
}


<div class="row m-t-sm">
    <div class="col-lg-3">
        <div class="ibox">
            <div class="ibox-content">
                <h5>Hoy</h5>
                <h1 class="no-margins">@Model.TodayAppointmentsCount</h1>
                <div class="stat-percent font-bold text-info"><i class="fa fa-users""></i></div>
                <small>Total de Visitas</small>
            </div>
        </div>
    </div>
    <div class="col-lg-3">
        <div class="ibox">
            <div class="ibox-content">
                <h5>Este Mes</h5>
                <h1 class="no-margins">@Model.ThisMonthAppointmentsCount</h1>
                <div class="stat-percent font-bold text-info"><i class="fa fa-users"></i></div>
                <small>Total de Visitas</small>
            </div>
        </div>
    </div>
    <div class="col-lg-3">
        <div class="ibox">
            <div class="ibox-content">
                <h5>Ingresos del Dia</h5>
                <h1 class="no-margins">@Model.TodayIncome.ToString("#,##0.00")</h1>
                <div class="stat-percent font-bold text-navy"><i class="fa fa-money"></i></div>
                <small>Total de Ingresos</small>
            </div>
        </div>
    </div>
    <div class="col-lg-3">
        <div class="ibox">
            <div class="ibox-content">
                <h5>Ingresos del Mes</h5>
                <h1 class="no-margins">@Model.ThisMonthIncome.ToString("#,##0.00")</h1>
                <div class="stat-percent font-bold text-navy"><i class="fa fa-money"></i></div>
                <small>Total de ingresos</small>
            </div>
        </div>
    </div>
</div>

<div class="row">

    <div class="col-lg-12">
        <div class="ibox float-e-margins">
            <div class="ibox-title">
                <h5>Citas del dia </h5>
                <div class="ibox-tools">
                    <a class="collapse-link">
                        <i class="fa fa-chevron-up"></i>
                    </a>
                </div>
            </div>
            <div class="ibox-content">
                <div class="table-responsive">
                    <table class="table table-striped jq-Datatable">
                        <thead>
                            <tr>
                                <th>No</th>
                                <th>Paciente</th>
                                <th>Telefono</th>
                                <th>Odontologo</th>
                                <th>Hora</th>
                                <th>Estado</th>
                                @if (role.Contains("Secretaria"))
                                {
                                    <th> </th>
                                }
                            </tr>
                        </thead>
                        <tbody>
                            @if(Model.TodayAppointment != null) {
                                var count = 1;
                                foreach (var appointment in Model.TodayAppointment) {

                                <tr>
                                    <td>@count</td>
                                    <td>@(appointment.Patient.Name+" "+ appointment.Patient.LastName)</td>
                                    <td>@appointment.Patient.Phones.FirstOrDefault(x => x.Primary == 1 ).Number</td>
                                    <td>@appointment.User.Name @appointment.User.LastName</td>
                                    <td>@(appointment.StartDate.Hour != 12 && appointment.StartDate.Hour % 12 < 10 ? "0" : " ")@(appointment.StartDate.Hour > 12 ? appointment.StartDate.Hour % 12 : appointment.StartDate.Hour):@(appointment.StartDate.Minute > 10 ? appointment.StartDate.Minute.ToString() :"0"+ appointment.StartDate.Minute) @(appointment.StartDate.Hour >= 12 ? "PM":"AM")</td>
                                    <td>@(appointment.IsConfirm?"Confirmada":"Pendiente")</td>
                                    @if (role.Contains("Secretaria"))
                                    {
                                      
                                   
                                    <td>
                                        @if (!appointment.IsConfirm)
                                        {
                                            <a class="btn btn-default btn-xs confirm-appointment" data-confirm="@appointment.Id" data-toggle="tooltip" title="Confirmar Cita"><i class="fa fa-check"></i></a>
                                        }
                                        @if (appointment.IsPaid)
                                        {
                                            <a class="btn btn-success btn-xs" href="@Url.Action("InvoiceReprint","Invoice",new { id = appointment.Id})" data-toggle="tooltip" title="Imprimir Factura"><i class="fa fa-print"></i></a>
                                            <a class="btn btn-danger btn-xs  anular" data-delete="@appointment.Id" data-toggle="tooltip" title="Anular Factura"><i class="fa fa-repeat"></i></a>
                                        }
                                        else
                                        {
                                            <a class="btn btn-primary btn-xs" href="@Url.Action("Invoice","Invoice",new { id = appointment.Id})" data-toggle="tooltip" title="Facturar"><i class="fa fa-money"></i></a>
                                            <a class="btn btn-danger btn-xs delete" data-delete="@appointment.Id" data-toggle="tooltip" title="Cancelar Cita"><i class="fa fa-times"></i></a>
                                        }
                                    </td>
                                    }
                                </tr>

                                    count += 1;
                                }

                            }
                        </tbody>
                    </table>
                </div>

            </div>
        </div>
    </div>

</div>

@section Styles {
    <style>
        .confirm-appointment,
        .delete{}
    </style>

}

@section Scripts {
    @Scripts.Render("~/plugins/sparkline")
    @Scripts.Render("~/plugins/flot")

    <script type="text/javascript">
        $(document).ready(function () {

            $(".jq-Datatable")
              .dataTable({
                  language: {
                      url: "../Scripts/plugins/dataTables/Spanish.json"
                  },
                  dom: '<"html5buttons"B>lTfgitp',
                  buttons: [
                      { extend: "copy", exportOptions: { columns: [1, 2, 3] } },
                      { extend: "csv", exportOptions: { columns: [1, 2, 3] } },
                      { extend: "excel", exportOptions: { columns: [1, 2, 3] } },
                      { extend: "pdf", exportOptions: { columns: [1, 2, 3] } },
                      {
                          extend: "print",
                          exportOptions: { columns: [1, 2, 3] },
                          customize: function (win) {
                              $(win.document.body).addClass("white-bg");
                              $(win.document.body).css("font-size", "10px");

                              $(win.document.body)
                                  .find("table")
                                  .addClass("compact")
                                  .css("font-size", "inherit");
                          }
                      }
                  ],
                  "order": []
              });

            $('body').on('click', '.delete', function () {
               var id =  parseInt($(this).attr('data-delete'));
               let Appointment = { appointmentId: id }

               swal({
                   title: "Desea Cancelar la Cita?",
                   text: "",
                   type: "warning",
                   showCancelButton: true,
                   confirmButtonClass: "btn-warning",
                   confirmButtonText: "Ok!",
                   closeOnConfirm: false
               },
               function (isConfirm) {
                   if (isConfirm) {
                       ajaxCall(Appointment, '@Url.Action("CancelAppointment","Agenda")', "Cita Cancelada");
                   }
               });

                return false;
            });

            $('body').on('click', '.anular', function () {
                var id = parseInt($(this).attr('data-delete'));
                let Appointment = { appointmentId: id }

                swal({
                    title: "Anular Factura?",
                    text: "",
                    type: "warning",
                    showCancelButton: true,
                    confirmButtonClass: "btn-warning",
                    confirmButtonText: "Ok!",
                    closeOnConfirm: false
                },
                function (isConfirm) {
                    if (isConfirm) {
                        ajaxCall(Appointment, '@Url.Action("CancelInvoice","Invoice")', "Factura Anulada");
                    }
                });
                return false;
        
            });

            $('body').on('click', '.confirm-appointment', function () {
                
                var id = parseInt( $(this).attr('data-confirm'));
                let Appointment = { appointmentId: id }

                swal({
                    title: "Confirmar Cita?",
                    text: "",
                    type: "info",
                    showCancelButton: true,
                    confirmButtonClass: "btn-success",
                    confirmButtonText: "Ok!",
                    closeOnConfirm: false
                },
                function (isConfirm) {
                    if (isConfirm) {
                        ajaxCall(Appointment, '@Url.Action("ConfirmAppointment", "Agenda")', "Cita Confirmada");
                    }
                });

                return false;
            });

            function ajaxCall(Appointment, url, message) {
                let jsondata = JSON.stringify(Appointment);
                $.ajax({
                    url: url,
                    dataType: 'json',
                    contentType: 'application/json; charset=UTF-8',
                    type: 'POST',
                    data: jsondata,
                    success: function (data) {
                        swal({
                            title:message,
                            text: "",
                            type: "success",
                            confirmButtonClass: "btn-success",
                            confirmButtonText: "Ok!",
                            closeOnConfirm: true
                        },
                       function (isConfirm) {
                           if (isConfirm) {
                               location.reload();
                           }
                        });
                    },
                    error: function (xhr, ajaxOptions, thrownError) {
                        location.reload();
                    }
                });
            }

        });
    </script>
}

WebApp/Views/Home/ErrorPage.cshtml
@model ErrorViewModel

@{
    if (Model != null)
    {
        <div class="ibox-content">
            <h2 class="modal-title text-center font-bold">MRChange Plus - Error <i class="fa fa-warning modal-icon text-warning"></i></h2>
        </div>
        <div class="jumbotron">
            <div class="alert alert-danger error-content">
                <h3 align="center">
                    <strong>@Model.Messages</strong>
                </h3>
            </div>
        </div>
            if (Model.Referrer != null)
            {
                <a href="@Model.Referrer" style="margin-top: 20px !important;" class="btn btn-primary pt-2"><i class="fa fa-arrow-left"></i> Regresar </a>
            }
       
    }
}